
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PNACCompetitionsDbFirst.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Catch
{

    public int CatchId { get; set; }

    public int EntryId { get; set; }

    public int FishId { get; set; }

    public System.DateTime Date { get; set; }

    public bool CatchAndRelease { get; set; }

    public int Number { get; set; }

    public double Weight { get; set; }

    public int Length { get; set; }



    public virtual Fish Fish { get; set; }

    public virtual Entry Entry { get; set; }

}

}
