//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNACCompetitionsDbFirst.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition()
        {
            this.Entries = new HashSet<Entry>();
        }
    
        public int CompetitionId { get; set; }
        public int ClubId { get; set; }
        public int EnvironmentId { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string Name { get; set; }
        public System.DateTime Start { get; set; }
        public string Venue { get; set; }
        public Nullable<System.DateTime> WeighInTime { get; set; }
        public string WeighInVenue { get; set; }
        public string DayType { get; set; }
    
        public virtual Environment Environment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entry> Entries { get; set; }
    }
}
