
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PNACCompetitionsDbFirst.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Fish
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Fish()
    {

        this.Environments = new HashSet<Environment>();

        this.Catches = new HashSet<Catch>();

    }


    public int FishId { get; set; }

    public string Name { get; set; }

    public int Minimum { get; set; }

    public int Maximum { get; set; }

    public double Difficulty { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Environment> Environments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Catch> Catches { get; set; }

}

}
