
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PNACCompetitionsDbFirst.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Season
{

    public int SeasonId { get; set; }

    public int ClubId { get; set; }

    public System.DateTime End { get; set; }

    public System.DateTime Start { get; set; }



    public virtual Club Club { get; set; }

}

}
